# Generated by Django 4.2.21 on 2025-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbt_level_class',
            name='col_grade',
            field=models.CharField(max_length=10),
        ),
    ]
