# Generated by Django 4.2.21 on 2025-06-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0002_alter_lbt_level_class_col_grade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account_balances',
            table='Account_balances',
        ),
    ]
