# Generated by Django 4.2.21 on 2025-06-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0003_alter_account_balances_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lbt_exchange_rate',
            name='col_base_curr_shortcode',
        ),
        migrations.RemoveField(
            model_name='lbt_exchange_rate',
            name='col_dest_curr_shortcode',
        ),
    ]
