# Generated by Django 4.2.21 on 2025-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0004_remove_lbt_exchange_rate_col_base_curr_shortcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbt_customer',
            name='col_phys_add',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
