# Generated by Django 4.2.21 on 2025-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0005_alter_lbt_customer_col_phys_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbt_level_class',
            name='col_class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lbt_level_class',
            name='col_grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lbt_progresssion',
            name='col_co_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lbt_progresssion',
            name='col_grade',
            field=models.CharField(default=3, max_length=100),
        ),
    ]
