# Generated by Django 4.2.21 on 2025-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0006_alter_lbt_level_class_col_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lbt_grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_grade_name', models.CharField(max_length=100)),
            ],
        ),
    ]
