# Generated by Django 4.2.21 on 2025-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0007_lbt_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbt_level_class',
            name='col_level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
