# Generated by Django 4.2.21 on 2025-06-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0008_lbt_level_class_col_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbt_registration',
            name='col_grade',
            field=models.CharField(default=3, max_length=100),
        ),
    ]
