# Generated by Django 4.2.21 on 2025-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0009_alter_lbt_registration_col_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltb_session',
            name='col_session_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
