# Generated by Django 4.2.21 on 2025-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezfees', '0010_alter_ltb_session_col_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltb_ordinance',
            name='col_ordinance_name',
            field=models.CharField(max_length=100),
        ),
    ]
