from django.urls import path
from .views import home,currency,accounting_period,revenue_objects,revenue_structure, login_user,download_customer_list_file,fetch_revenue_groups,fetch_payment_methods,fetch_revenue_groups2,fetch_revenue_structure2,fetch_records,save_invoice,group,save_invoices,save_group_codes,invoiced_list,payment_plan,download_balance_upload_file,upload_balances,adjustments, receipting_adjustments,delete_session,print_invoice,fees_statements,statements,login,account_balances,receipt,remmittance_list,age_analysis,assign_revenue,revenue_invoicing,top_navigation,register,save_register,registration_list,save_registration
from .views import  single_customer,exchange_rates,login_user, exchange_rate_list,add_school,cost_centres,chat_of_accounts,session,ordinance,payment_methods,download_customer_template,upload_customer,revenue_group,revenue_objects_list,fetch_revenue_codes,fetch_group_codes,fetch_ordinance_codes,fetch_session_codes,fetch_customer_no,fetch_currency_code,currency_list,session_list,school_details_list,cost_centre_list,revenue_group_list,accounts,customer_list, remmitance_detail, ordinance_details, invoice_detail,accounts_list,fetch_revenue_groups2, save_remittances,save_remmittances,debtors,bulk_invoices,invoice_bulk,save_levels,progress_class,save_progression,save_classes
from .views import filter_records,fetch_grades,fetch_session_year,fetch_session_code,fetch_session_id,sales_report,download_manual,fetch_cur,save_remit,save_grade, login_user
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Beezfees'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('', login_user, name='login_user'),
    path('logout/', views.logoutuser, name='logout'),
    path('home/', home, name='home'),
    path('download_manual/', download_manual, name='download_manual'),
    path('currency/', currency, name='currency'),
    path('exchange_rates/', exchange_rates, name='exchange_rates'),
    path('accounting_period/', accounting_period, name='accounting_period'),
    path('revenue_objects/', revenue_objects, name='revenue_objects'),
    path('revenue_structure/', revenue_structure, name='revenue_structure'),
    path('revenue_group/', revenue_group, name='revenue_group'),
    path('download_customer_list_file/', download_customer_list_file, name='download_customer_list_file'),
    #path('upload_opening_balances/', upload_opening_balances, name='upload_opening_balances'),
    path('single_customer/', single_customer, name='single_customer'),
    path('exchange_rate_list/', exchange_rate_list, name='exchange_rate_list'),
    path('customer_list/', customer_list, name='customer_list'),
    path('accounts_list/', accounts_list, name='accounts_list'),
    path('add_school/', add_school, name='add_school'),
    path('cost_centres/', cost_centres, name='cost_centres'),
    path('chat_of_accounts/', chat_of_accounts, name='chat_of_accounts'),
    path('session/', session, name='session'),
    path('ordinance/', ordinance, name='ordinance'),
    path('ordinance_details/',  ordinance_details, name='ordinance_details'),
    path('payment_methods/', payment_methods, name='payment_methods'),
    path('download_customer_template/', download_customer_template, name='download_customer_template'),
    path('upload_customer/', upload_customer, name='upload_customer'),
    path('revenue_objects_list/', revenue_objects_list, name='revenue_objects_list'),
    path("save-classes",save_classes, name="save_classes"),
    path('fetch_revenue_codes/', fetch_revenue_codes, name='fetch_revenue_codes'),
    path('fetch_group_codes/', fetch_group_codes, name='fetch_group_codes'),
    path('fetch_ordinance_codes/', fetch_ordinance_codes, name='fetch_ordinance_codes'),
    path('fetch_session_codes/', fetch_session_codes, name='fetch_session_codes'),
   # path('customer_accounts/', customer_accounts, name='customer_accounts'),
    path('fetch_customer_no/', fetch_customer_no, name='fetch_customer_no'),
    path('fetch_currency_codes/', fetch_currency_code, name='fetch_currency_code'),
    path('fetch_revenue_groups/', fetch_revenue_groups, name='fetch_revenue_groups'),
    path('fetch_revenue_groups2/', fetch_revenue_groups2, name='fetch_revenue_groups2'),
    path('currency_list/', currency_list, name='currency_list'),
    path('session_list/', session_list, name='session_list'),
    path('cost_centre_list/', cost_centre_list, name='cost_centre_list'),
    path('school_details_list/', school_details_list, name='school_details_list'),
    path('revenue_group_list/', revenue_group_list, name='revenue_group_list'),
    path('accounts/', accounts, name='accounts'),
    path('favicon.ico', RedirectView.as_view(url='')),
    path('remmitance_detail/', remmitance_detail, name='remmitance_detail'),
    path('invoice_detail/', invoice_detail, name='invoice_detail'),
    
    path('fetch_revenue_structure2/', fetch_revenue_structure2, name='fetch_revenue_structure2'),
    path('fetch_records/', fetch_records, name='fetch_records'),
    path('fetch_grades/', fetch_grades, name='fetch_grades'),
    path('save_invoices/', save_invoices, name='save_invoices'),
    path('save_invoice/', save_invoice, name='save_invoice'),
    path('group/', group, name='group'),
    path('save_group_codes/', save_group_codes, name='save_group_codes'),
    path('save_remittances/', save_remittances, name='save_remittances'),
    path('invoiced_list/', invoiced_list, name='invoiced_list'),
    #path('account_balances/', account_balances, name='account_balances'),
    path("account_balance/",views.balance,name="account_balances"),
    path('save_remmittances/', save_remmittances, name='save_remmittances'),
    path('payment_plan/',payment_plan, name='payment_plan'),
    path('download_balance_upload_file/', download_balance_upload_file, name='download_balance_upload_file'),
    path('upload_balances/', upload_balances, name='upload_balances'),
    path('adjustments/', adjustments, name='adjustments'),
    path(' receipting_adjustments/',  receipting_adjustments, name='receipting_adjustments'),
    path('update_session/', views.update_session, name='update_session'),
    path('delete_session/', views.delete_session, name='delete_session'),
    path('fees_statements/<str:account_number>/', views.fees_statements, name='fees_statements'),
    path('statements/', statements, name='statements'),
    path('print_invoice/<str:invoice_id>/', views.print_invoice, name='print_invoice'),
    path('receipt/<str:cust_num>', views.receipt, name='receipt'),
    path('remmittance_list/', remmittance_list, name='remmittance_list'),
    path('age_analysis', views.age_analysis, name='age_analysis'),
    path('assign_revenue', views.assign_revenue, name='assign_revenue'),
    #path('exchange_rate', views.exchange_rate, name='exchange_rate'),
    path('fetch_payment_methods/', views.fetch_payment_methods, name='fetch_payment_methods'),
    path('revenue_invoicing/', revenue_invoicing, name='revenue_invoicing'),
    path('register/', register, name='register'),
    path('debtors/', debtors, name='debtors'),
    path('top_navigation/', top_navigation, name='top_navigation'),
    path('bulk_invoices/', bulk_invoices, name='bulk_invoices'),
    path('invoice_bulk/', invoice_bulk, name='invoice_bulk'),
    path('save_register/', save_register, name='save_register'),
    path('registration_list/', registration_list, name='registration_list'),
    path('save_levels/', save_levels, name='save_levels'),
    path('save_grades',save_grade, name='save_grades'),
    path('save_registration/', save_registration, name='save_registration'),
    path('progress_class/', progress_class, name='progress_class'),
    path('filter_records/', filter_records, name='filter_records'),
    path('fetch_session_code/', fetch_session_code, name='fetch_session_code'),
    path('fetch_session_year/', fetch_session_year, name='fetch_session_year'),
    path('fetch_session_id/', fetch_session_id, name='fetch_session_id'),
    path('save_progression/',save_progression, name='save_progression'),
    path('sales_report/', sales_report, name='sales_report'),
  
 
    path('save_remit/', save_remit, name='save_remit'),
    #path('add_users/', add_users, name='add_users'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
